config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get "up" => "rails/health#show", as: :rails_health_check

  scope "/l/:language_iso" do
    resources :words, path: "", only: [:index, :show, :destroy], param: :value
  end

  resources :translations, path: "/t", only: [:new, :create, :destroy]
  resources :exercises, path: "/e", only: [:index, :create, :show], param: :url_identifier do
    resources :items, path: "/i", only: [:show, :edit, :update], param: :url_identifier, module: :exercises
  end

  resources :mojinizers, only: :show, param: :value

  root to: "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/exercise.rb
class Exercise < ApplicationRecord
  attr_readonly :url_identifier

  belongs_to :user

  has_many :exercise_items

  validates :started_at, presence: true
  validates :completion_percentage, :score_percentage, numericality: { greater_than_or_equal_to: 0,
                                                                       less_than_or_equal_to: 100 }

  scope :antichronical, -> { order(started_at: :desc) }

  def ended?
    ended_at.present?
  end

  def find_next_exercise_item
    exercise_items.ordered_by_position.find_by(given_answer: nil)
  end

  def update_progress
    all_exercise_items = exercise_items

    completion_percentage = 0
    score_percentage = 0
    ended_at = self.ended_at

    answered_items = all_exercise_items.find_all(&:answered?)

    if answered_items.any?
      completion_percentage =  answered_items.size * 100 / all_exercise_items.size
      score_percentage = answered_items.sum(&:score) / answered_items.size
    end

    if completion_percentage == 100
      ended_at ||= Time.zone.now
    end

    update(completion_percentage:, score_percentage:, ended_at:)
  end

  def to_param
    url_identifier
  end
end

app/models/exercise_item.rb
class ExerciseItem < ApplicationRecord
  belongs_to :exercise

  validates :position,
            :from_language_iso,
            :from_word_value,
            :to_language_iso,
            :possible_solutions,
            :score,
            presence: true

  validates :score, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  validates :position, uniqueness: { scope: :exercise_id }

  scope :ordered_by_position, -> { order(position: :asc) }
  # scope :answered, -> { where.not(given_answer: nil) }

  def answered?
    given_answer.present?
  end

  def answered_with(value)
    raise "Cannot answer again!" if given_answer.present?

    if value.present?
      given_answer = value
      score = given_answer.in?(possible_solutions) ? 100 : 0
      update(given_answer:, score:)
    else
      errors.add(:given_answer, :blank) && false
    end
  end

  def to_param
    url_identifier
  end
end

app/models/language.rb
class Language < ApplicationRecord
  has_many :words, dependent: :destroy

  validates :iso, presence: true
  validates :iso, uniqueness: true

  scope :ordered_by_iso, -> { order(iso: :asc) }

  def to_param
    iso
  end
end

app/models/translation.rb
class Translation < ApplicationRecord
  belongs_to :word
  belongs_to :target_word, class_name: "Word"

  scope :latest, -> { order(created_at: :desc) }

  def twin
    Translation.find_by(word: target_word, target_word: word)
  end

  def destroy_with_twin
    twin&.destroy
    destroy
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :exercises
end

app/models/word.rb
class Word < ApplicationRecord
  belongs_to :language
  belongs_to :also_written_as, optional: true, class_name: "Word"

  has_many :translations, dependent: :destroy
  # has_many :translation_sources, dependent: :destroy, class_name: "Translation", inverse_of: :target_word

  validates :value, presence: true
  validates :value, uniqueness: { scope: :language_id }

  scope :latest, -> { order(created_at: :desc) }
  scope :of_iso, ->(iso) { where(language: Language.find_by(iso:)) }

  def to_param
    value
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/exercises/items_controller.rb
class Exercises::ItemsController < ApplicationController
  before_action :set_exercise
  before_action :set_exercise_item

  def show
    redirect_to edit_exercise_item_path(@exercise, @exercise_item) if !@exercise_item.answered?

    @next_exercise_item = @exercise.find_next_exercise_item
  end

  def edit
    redirect_to exercise_item_path(@exercise, @exercise_item) if @exercise_item.answered?
  end

  def update
    if @exercise_item.answered_with(exercise_item_params[:given_answer])
      @exercise.reload.update_progress
      redirect_to exercise_item_path(@exercise, @exercise_item)
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def exercise_item_params
    params.require(:exercise_item).permit(:given_answer)
  end

  def set_exercise
    @exercise = current_user.exercises.find_by!(url_identifier: params[:exercise_url_identifier])
  end

  def set_exercise_item
    @exercise_item = @exercise.exercise_items.find_by!(url_identifier: params[:url_identifier])
  end
end

app/controllers/exercises_controller.rb
class ExercisesController < ApplicationController
  def index
    @exercises = current_user.exercises.antichronical
  end

  def show
    @exercise = current_user.exercises.find_by!(url_identifier: params[:url_identifier])
  end

  def create
    exercise = current_user.exercises.new(started_at: Time.zone.now)

    Translation.where(word: Word.of_iso("en"), target_word: Word.of_iso("ja"))
               .sample(5)
               .each_with_index do |translation, index|
      possible_solutions = Word.where(id: translation.word.translations.where(target_word: Word.of_iso("ja")).select(:target_word_id)).pluck(:value)

      exercise.exercise_items.new(
        position: index,
        from_language_iso: "en",
        from_word_value: translation.word.value,
        to_language_iso: "ja",
        possible_solutions:
      )
    end

    exercise.save

    redirect_to exercise_path(exercise)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_action :authenticate_user!, only: :index

  def index
    @languages = Language.ordered_by_iso
  end
end

app/controllers/mojinizers_controller.rb
class MojinizersController < ApplicationController
  def show
    @value = params[:value]
  end
end

app/controllers/translations_controller.rb
class TranslationsController < ApplicationController
  def new
    @form = TranslationForm.new(params:)
  end

  def create
    @form = TranslationForm.new(params:)

    if @form.save
      redirect_to word_path(@form.source_word.language, @form.source_word)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @translation = Translation.find(params[:id])

    @translation.destroy_with_twin

    redirect_to word_path(@translation.word.language, @translation.word)
  end
end

app/controllers/words_controller.rb
class WordsController < ApplicationController
  before_action :set_language

  def index
    @words = @language.words.latest.limit(10)
  end

  def show
    @word = @language.words.find_by!(value: params[:value])
  end

  def destroy
    @word = @language.words.find_by!(value: params[:value])

    @word.destroy

    redirect_to words_path(@word.language)
  end

  private

  def set_language
    @language = Language.find_by!(iso: params[:language_iso])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/exercises/_list.html.erb
<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Started</th>
      <th>Ended</th>
      <th>Completion</th>
      <th>Score</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% exercises.each do |exercise| %>
      <tr>
        <td><%= exercise.url_identifier %></td>
        <td><%= exercise.started_at %></td>
        <td><%= exercise.ended_at %></td>
        <td><%= exercise.completion_percentage %></td>
        <td><%= exercise.score_percentage %></td>
        <td><%= link_to "Show", exercise %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/exercises/index.html.erb
/<%= link_to "Home", root_path, class: "link" %>

<h1>Exercises</h1>

<h2>Latest exercises</h2>

<%= render "exercises/list", exercises: @exercises %>

<%= button_to "Start new exercise", exercises_path, class: "button" %>

app/views/exercises/items/edit.html.erb
/<%= link_to "Home", root_path, class: "link" %>/<%= link_to "Exercises", exercises_path, class: "link" %>/<%= link_to "##{@exercise.url_identifier}", @exercise, class: "link" %>

<%= turbo_frame_tag dom_id(@exercise, :current_exercise_item) do %>
  <%= form_with(model: @exercise_item, url: exercise_item_path(@exercise, @exercise_item)) do |f| %>
    <%= @exercise_item.from_language_iso %>
    <%= @exercise_item.from_word_value %>

    <%= f.text_field :given_answer %>
    <% if f.object.errors.include?(:given_answer) %>
      <span class="text-red-400">
        <%= f.object.errors.messages_for(:given_answer).join(", ") %>
      </span>
    <% end %>

    <%= f.submit nil, class: "button" %>
  <% end %>
<% end %>

app/views/exercises/items/show.html.erb
/<%= link_to "Home", root_path, class: "link" %>/<%= link_to "Exercises", exercises_path, class: "link" %>/<%= link_to "##{@exercise.url_identifier}", @exercise, class: "link" %>

<%= turbo_frame_tag dom_id(@exercise, :current_exercise_item) do %>
  <div>
    <%= @exercise_item.from_language_iso %>
    <%= @exercise_item.from_word_value %>

    <%= @exercise_item.given_answer %>
    <%= @exercise_item.possible_solutions.join(", ") %>
    <%= @exercise_item.score %>
  </div>

  <div>
    <% if @next_exercise_item.present? %>
      <%= link_to "Next exercise item", exercise_item_path(@exercise, @next_exercise_item), class: "button" %>
    <% else %>
      <%= link_to "Finish", exercise_path(@exercise), class: "button", "data-turbo-frame": "_top" %>
    <% end %>
  </div>
<% end %>

app/views/exercises/show.html.erb
/<%= link_to "Home", root_path, class: "link" %>/<%= link_to "Exercises", exercises_path, class: "link" %>

<h1>Exercise #<%= @exercise.url_identifier %></h1>

<table>
  <thead>
    <tr>
      <th>Completion</th>
      <th>Score</th>
      <th>Ended at</th>
    </tr>
  </thead>

  <tbody>
    <tr>
      <td><%= @exercise.completion_percentage %></td>
      <td><%= @exercise.score_percentage %></td>
      <td><%= @exercise.ended_at %></td>
    </tr>
  </tbody>
</table>

<% if @exercise.ended? %>
  <h2>Items</h2>

  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>From</th>
        <th>Word value</th>
        <th>To</th>
        <th>Possible solutions</th>
        <th>Given solution</th>
        <th>Score</th>
      </tr>
    </thead>

    <tbody>
      <% @exercise.exercise_items.each do |exercise_item| %>
        <tr>
          <td><%= exercise_item.position %></td>
          <td><%= exercise_item.from_language_iso %></td>
          <td><%= exercise_item.from_word_value %></td>
          <td><%= exercise_item.to_language_iso %></td>
          <td><%= exercise_item.possible_solutions.join(", ") %></td>
          <td><%= exercise_item.given_answer %></td>
          <td><%= exercise_item.score %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <%= turbo_frame_tag dom_id(@exercise, :current_exercise_item), src: exercise_item_path(@exercise, @exercise.find_next_exercise_item) %>
<% end %>

app/views/home/index.html.erb
<%= link_to "Home", root_path, class: "link" %>

<h1>Home</h1>

<h2>Languages</h2>

<%= render "languages/list", languages: @languages %>

app/views/languages/_list.html.erb
<div class="flex gap-2">
  <% languages.each do |language| %>
    <%= link_to words_path(language), class: "opacity-70 bg-gray-100 rounded-3xl border-4 hover:border-red-300 hover:opacity-100 transition" do %>
      <div class="flex gap-y-2 flex-col items-center justify-center w-36 h-36">
        <div class="text-4xl"><%= language.iso %></div>
        <div class="flex flex-col text-xs items-center">
          <div><%= language.words.size %> words</div>
          <div><%= Translation.where(word: language.words).size %> translations</div>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sakura</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container mx-auto px-5 flex flex-col">
    <div class="flex justify-between">
      <div class="main-logo">Sakura</div>

      <div>
        <% if user_signed_in? %>
          <%= button_to "Sign out", destroy_user_session_path, method: :delete %>
        <% else %>
          <%= link_to "Sign in", new_user_session_path %>
        <% end %>
      </div>
    </div>
    <main>
      <%= yield %>
    </main>
  </body>
</html>

app/views/mojinizers/show.html.erb
Romaji: <%= @value.romaji %>
Hiragana: <%= @value.hiragana %>
Katakana: <%= @value.katakana %>

app/views/translations/_list.html.erb
<% local_assigns.with_defaults(show_from: true) => { show_from: } %>
<table>
  <thead>
    <tr>
      <% if show_from %>
        <th colspan="2">From</th>
      <% end %>
      <th colspan="2">To</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% translations.each do |translation| %>
      <tr>
        <% if show_from %>
          <td><%= link_to translation.word.value, word_path(translation.word.language.iso, translation.word), class: "link" %></td>
          <td><%= link_to translation.word.language.iso, words_path(translation.word.language.iso), class: "link" %>
        <% end %>

        </td>
        <td><%= link_to translation.target_word.value, word_path(translation.target_word.language.iso, translation.target_word), class: "link" %></td>
        <td><%= link_to translation.target_word.language.iso, words_path(translation.target_word.language.iso), class: "link" %></td>
        <td>
          <%= button_to "Delete translation", translation_path(translation), method: :delete, class: "dangerous-link", data: { "turbo-confirm": "Are you sure?" } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/translations/new.html.erb
/<%= link_to "Home", root_path, class: "link" %>/New translation

<h1>New translation</h1>

<%= form_with(model: @form) do |f| %>
  <div class="flex">
    <div class="flex-col">
      <div class="flex flex-col">
        <span>From</span>
        <%= f.label :source_word_language_iso, class: "sr-only" %>
        <%= f.select :source_word_language_iso, f.object.target_word_language_options, include_blank: "Select" %>
        <% if f.object.errors.include?(:source_word_language_iso) %>
          <span class="text-red-300">
            <%= f.object.errors.messages_for(:source_word_language_iso).join(", ") %>
          </span>
        <% end %>
      </div>

      <div>
        <%= f.label :source_word_value, class: "sr-only" %>
        <%= f.text_field :source_word_value %>
        <% if f.object.errors.include?(:source_word_value) %>
          <span class="text-red-300">
            <%= f.object.errors.messages_for(:source_word_value).join(", ") %>
          </span>
        <% end %>
      </div>
    </div>

    <div class="flex-col">
      <div class="flex flex-col">
        <span>To</span>
        <%= f.label :target_word_language_iso, class: "sr-only" %>
        <%= f.select :target_word_language_iso, f.object.target_word_language_options, include_blank: "Select" %>
        <% if f.object.errors.include?(:target_word_language_iso) %>
          <span class="text-red-300">
            <%= f.object.errors.messages_for(:target_word_language_iso).join(", ") %>
          </span>
        <% end %>
      </div>

      <div>
        <%= f.label :target_word_value, class: "sr-only" %>
        <%= f.text_field :target_word_value %>
        <% if f.object.errors.include?(:target_word_language_iso) %>
          <span class="text-red-300">
            <%= f.object.errors.messages_for(:target_word_language_iso).join(", ") %>
          </span>
        <% end %>
      </div>
    </div>
  </div>

  <div>
    <%= f.submit nil, class: "button" %>
  </div>
<% end %>

app/views/words/_list.html.erb
<table>
  <thead>
    <tr>
      <th>Word</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% words.each do |word| %>
      <tr>
        <td><%= word.value %></td>
        <td><%= link_to "Show", word_path(word.language, word), class: "link" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/words/index.html.erb
/<%= link_to "Home", root_path, class: "link" %>

<h1><%= @language.iso %></h1>

<h2>Latest words</h2>

<%= render "list", words: @words %>

app/views/words/show.html.erb
<div class="flex flex-col gap-y-4">
  <div>
    /<%= link_to "Home", root_path, class: "link" %>/<%= link_to @word.language.iso, words_path(@word.language), class: "link" %>/<%= @word.value %>
  </div>

  <div class="flex items-baseline gap-x-1">
    <h1><%= @word.value %></h1>
    <% if @word.also_written_as.present? %>
      <span class="text-gray-500">
        (<%= @word.also_written_as.value %>)
      </span>
    <% end %>
  </div>

  <h2>Translations</h2>

  <div>
    <%= render "translations/list", translations: @word.translations, show_from: false %>
  </div>

  <div>
    <%= link_to "Add translation", new_translation_path(translation: { source_word_language_iso: @word.language.iso, source_word_value: @word.value }), class: "button" %>
  </div>

  <div>
    <%= button_to "Delete word", word_path(@word.language, @word), method: :delete, class: "dangerous-link", data: { "turbo-confirm": "Are you sure?" } %>
  </div>
</div>